name = "autouz"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[triggers]
crons = ["0 */2 * * *"]

[[kv_namespaces]]
binding = "VIDEO_QUEUE"
id = "58d50a7063994480abcc1ec0705cbd28"
preview_id = "58d50a7063994480abcc1ec0705cbd28"

[[kv_namespaces]]
binding = "LOGS"
id = "597608c5497040b6825706ccac2a7a1b"
preview_id = "597608c5497040b6825706ccac2a7a1b"

[vars]
ENVIRONMENT = "development"
